### ISSUE TITLE
Impoper Git, Github and project setting

### ISSUE THREAD

**Issue by berabhishek** [snehal-chavan/project#1]
<h3> The following must be fixed in the project in order to continue </h3>

<ul>
     <li><h4>Project Name</h4>
             <li>The project name should not be <strong>"project"</strong>, instead it should be something that gives an idea about the domain of the project. </li>
             <li> Also change the file name <strong>"finalproject.java"</strong> and all the references of the file in every other file. You can do this quickly by <a href="http://wiki.netbeans.org/Refactoring" target="_blank">Refactoring</a> your code.
            </li>
      <li><h4>README.md</h4>
      <li>In the root project directory add a README.md to briefly explain what the project does and its modules.</li>
     </li>
      <li><h4>Unused Files</h4>
        <li>Unnecessary files should not be committed like <strong>"Hello.txt"</strong> </li> 
      </li>
      <li> <h4>Commit messages</h4>
        <li>The commit comments <i>git commit -m <strong>"&lt;message&gt;"</strong> </i> should be in present tense and should contain information on the major changes committed since previous version. They should NOT be "project"</li>
        
    </li> 
</ul>

**Comment by snehal-chavan** [comment]
nice issues

**Comment by berabhishek** [comment]
You can directly rename the github project from the settings panel. No need to delete and recreate another project.

**Comment by berabhishek** [comment]
You can directly rename the github project from the settings panel. No need to delete and recreate another project.
